# MZLA Notion Scripts Configuration
# See README for more information on the setup
[sync.mobile]
method = "github_project"
notion_tasks_id = "94ca27a3d7374a4fae6ad6d5c7a70a76"
notion_milestones_id = "637245a2c53b4d86a99c6e97006153df"
notion_sprints_id = "19e2df5d45ae803fa74ff4d6aa52f25f"

milestones_tracker_prefix = "[EPIC] "
milestones_github_label = "type: epic"
milestones_body_sync = false
milestones_body_sync_if_empty = true
tasks_body_sync = false
sprints_merge_by_name = true

[sync.mobile.properties]
notion_tasks_text_assignee = "GitHub Assignee"
notion_issue_field = "GitHub Issue"
notion_sprint_tracker_id = "GitHub ID"

[sync.mobile.repositories]

[sync.mobile.repositories.android]
repositories = [
  "thunderbird/thunderbird-android"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4AygBu"
github_milestones_project_id = "PVT_kwDOAOe9Jc4Ayf_S"

[sync.mobile.repositories.ios]
repositories = [
  "thunderbird/thunderbird-ios"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4A1aav"
github_milestones_project_id = "PVT_kwDOAOe9Jc4A1aX6"

[sync.bugzilla]
method = "bugzilla_project"
tracker_dry_run = true
notion_tasks_id = "20f2df5d45ae8004baeadc784d8f7ea4"
notion_milestones_id = "b0343817fb69424e85722e5d5fc8077b"
bugzilla_base = "https://bugzilla.mozilla.org"
milestones_tracker_prefix = "[meta] "

[sync.bugzilla.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_openclose = "Dates"
notion_tasks_milestone_relation = "Milestone"
notion_milestones_title = "Name"
notion_tasks_review_url = "Review URL"
notion_milestones_assignee = "Owner"
notion_issue_field = "Bugzilla URL"
notion_tasks_priority_values = ["P1", "P2", "P3", "P4", "P5"]

bugzilla_allowed_products = ["Thunderbird", "MailNews Core", "Calendar"]

### VAULT ###

[sync.support]
method = "github_labels"

notion_milestones_id = "2332df5d45ae80909305fe2278a14629"
notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae809696b3f0e6e6b1eead"

[sync.support.repositories]
repositories = [
    "thunderbird/knowledgebase-issues",
    "thunderbird/android-knowledgebase-issues",
    "thunderbird/ios-knowledgebase-issues",
    "thunderbird/tbpro-knowledgebase-issues",
]

[sync.support.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = ""
#notion_tasks_openclose = "GitHub Dates"
notion_tasks_priority = ""
notion_task_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_text_assignee = ""
notion_tasks_labels = ""
notion_tasks_repository = ""
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = ""
notion_milestones_dates = ""
notion_issue_field = "Bug Tracker"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]

[sync.desktop]
method = "bugzilla_project"
tracker_dry_run = true
notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"
notion_milestones_id = "2332df5d45ae80909305fe2278a14629"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae80ff92fbddd8eccb9060"

bugzilla_base = "https://bugzilla.mozilla.org"
milestones_tracker_prefix = "[meta] "

[sync.desktop.properties]
bugzilla_allowed_products = ["Thunderbird", "MailNews Core", "Calendar"]

notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = ""
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_text_assignee = ""
notion_tasks_labels = ""
notion_tasks_labels_text = "Keywords (Desktop)"
notion_tasks_whiteboard = "Whiteboard (Desktop)"
notion_tasks_repository = ""
notion_tasks_review_url = "Patch Review URL"
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = ""
notion_issue_field = "Bug Tracker"
notion_default_open_state = "Not started"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]

[sync.desktop.properties.bugzilla_map_state]
NEW = "Backlog"
UNCONFIRMED = "Backlog"
ASSIGNED = "In progress"
"IN REVIEW" = "In review"
REOPENED = "In progress"
RESOLVED = "Done"
VERIFIED = "Done"

"Backlog" = "NEW"
"Planning" = "NEW"
"In progress" = "ASSIGNED"
"In review" = "ASSIGNED"
"Approved" = "ASSIGNED"
"Done" = "RESOLVED"
"Canceled" = "RESOLVED"

[sync.services]
method = "github_project"
notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"
notion_milestones_id = "2332df5d45ae80909305fe2278a14629"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae8083af1dcda07b5c1eca"
milestones_issue_type = "Milestone"

[sync.services.repositories.pro]
repositories = [
    "thunderbird/addons-server",
    "thunderbird/appointment",
    "thunderbird/cloudops",
    "thunderbird/mailstrom",
    "thunderbird/observability-strategy",
    "thunderbird/pulumi",
    "thunderbird/send-suite",
    "thunderbird/services-ui",
    "thunderbird/services-utils",
    "thunderbird/tbpro-add-on",
    "thunderbird/thunderbird-accounts",
    "thunderbird/thunderbird-notifications",
    "thunderbird/thunderbird-website",
    "thunderbird/thundernest-ansible",
    #"thunderbird/assist",
    #"thunderbird/code-coverage",
    #"thunderbird/notion-scripts",
    #"thunderbird/stats",
    #"thunderbird/thunderblog",
    #"thunderbird/zendesk-config"
]
github_milestones_project_id = "PVT_kwDOAOe9Jc4BC48i"
github_tasks_project_id = "PVT_kwDOAOe9Jc4BC4_0"

[sync.services.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_text_assignee = ""
notion_tasks_labels = ""
notion_tasks_repository = ""
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = "Original Due Date"
notion_issue_field = "Bug Tracker"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]
