# MZLA Notion Scripts Configuration
# See README for more information on the setup
[sync.mobile]
method = "github_project"

notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"
notion_milestones_id = "2332df5d45ae80909305fe2278a14629"
notion_sprints_id = "2342df5d45ae806fb294c410dd0e71bd"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae80658b05c4e8a4819827"
milestones_issue_type = "Milestone"

milestones_body_sync = false
milestones_body_sync_if_empty = true
tasks_body_sync = false
sprints_merge_by_name = true

[sync.mobile.properties]
#notion_sprint_tracker_id = "GitHub ID"

notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
notion_tasks_planned_dates = "Original Due Date"
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_review_url = "Patch URL"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_sprint_relation = "Sprint"
notion_tasks_text_assignee = ""
notion_tasks_labels = ""
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = "Original Due Date"
notion_issue_field = "Bug URL"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]
notion_tasks_repository = "Ecosystem (Mobile)"

[sync.mobile.properties.notion_tasks_repository_map]
"thunderbird/thunderbird-android" = "Android"
"thunderbird/thunderbird-ios" = "iOS"

[sync.mobile.repositories.android]
repositories = [
  "thunderbird/thunderbird-android"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4AygBu"
github_milestones_project_id = "PVT_kwDOAOe9Jc4Ayf_S"

[sync.mobile.repositories.ios]
repositories = [
  "thunderbird/thunderbird-ios"
]
github_tasks_project_id = "PVT_kwDOAOe9Jc4A1aav"
github_milestones_project_id = "PVT_kwDOAOe9Jc4A1aX6"

[sync.support]
method = "github_labels"

notion_milestones_id = "2332df5d45ae80909305fe2278a14629"
notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae809696b3f0e6e6b1eead"

[sync.support.repositories]
repositories = [
    "thunderbird/knowledgebase-issues",
    "thunderbird/android-knowledgebase-issues",
    "thunderbird/ios-knowledgebase-issues",
    "thunderbird/tbpro-knowledgebase-issues",
]

[sync.support.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = ""
#notion_tasks_openclose = "GitHub Dates"
notion_tasks_priority = ""
notion_task_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_text_assignee = ""
notion_tasks_labels = ""
notion_tasks_repository = ""
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = ""
notion_milestones_dates = ""
notion_issue_field = "Bug URL"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]

[sync.desktop]
method = "bugzilla_project"
tracker_dry_run = true
notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"
notion_milestones_id = "2332df5d45ae80909305fe2278a14629"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae80ff92fbddd8eccb9060"

bugzilla_base = "https://bugzilla.mozilla.org"
milestones_tracker_prefix = "[meta] "

[sync.desktop.properties]
bugzilla_allowed_products = ["Thunderbird", "MailNews Core", "Calendar"]

notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = ""
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_text_assignee = ""
notion_tasks_labels = "Keywords (Desktop)"
notion_tasks_whiteboard = "Whiteboard (Desktop)"
notion_tasks_repository = ""
notion_tasks_review_url = "Patch URL"
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = ""
notion_issue_field = "Bug URL"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]

[sync.desktop.properties.bugzilla_map_state]
NEW = "Backlog"
UNCONFIRMED = "Backlog"
ASSIGNED = "In progress"
"IN REVIEW" = "In Review"
ACCEPTED = "Approved"
CHECKIN = "Ready to Publish"
REOPENED = "In progress"
RESOLVED = "Canceled"
"RESOLVED:FIXED" = "Done"
VERIFIED = "Canceled"
"VERIFIED:FIXED" = "Verified"

"Backlog" = "NEW"
"Planning" = "NEW"
"In progress" = "ASSIGNED"
"In Review" = "ASSIGNED"
"Approved" = "ASSIGNED"
"Ready to Publish" = "ASSIGNED"
"Done" = "RESOLVED"
"Canceled" = "RESOLVED"

[sync.services]
method = "github_project"
notion_tasks_id = "2332df5d45ae8072aa7aededaf161252"
notion_milestones_id = "2332df5d45ae80909305fe2278a14629"
notion_sprints_id = "2342df5d45ae806fb294c410dd0e71bd"

notion_team_id = "2332df5d45ae80bc8839d089f5c7f608"
notion_associated_team = "2332df5d45ae8083af1dcda07b5c1eca"
milestones_issue_type = "Milestone"

milestones_body_sync = false
milestones_body_sync_if_empty = true
milestones_create_from_tracker = true
tasks_body_sync = false

[sync.services.repositories.pro]
repositories = [
    "thunderbird/addons-server",
    "thunderbird/appointment",
    "thunderbird/cloudops",
    "thunderbird/mailstrom",
    "thunderbird/observability",
    "thunderbird/pulumi",
    "thunderbird/send-suite",
    "thunderbird/services-ui",
    "thunderbird/services-utils",
    "thunderbird/tbpro-add-on",
    "thunderbird/thunderbird-accounts",
    "thunderbird/thunderbird-notifications",
    "thunderbird/thunderbird-website",
    "thunderbird/thundernest-ansible",
    "thunderbird/routing",
    #"thunderbird/assist",
    #"thunderbird/code-coverage",
    #"thunderbird/notion-scripts",
    #"thunderbird/stats",
    #"thunderbird/thunderblog",
    #"thunderbird/zendesk-config"
]
github_milestones_project_id = "PVT_kwDOAOe9Jc4BC48i"
github_tasks_project_id = "PVT_kwDOAOe9Jc4BC4_0"

[sync.services.properties]
notion_tasks_title = "Name"
notion_tasks_assignee = "Assignee"
notion_tasks_dates = "Date"
notion_tasks_planned_dates = "Original Due Date"
#notion_tasks_openclose = ["Opened", "Closed"]
notion_tasks_priority = "Priority"
notion_tasks_review_url = "Patch URL"
notion_tasks_team = "Team"
notion_tasks_milestone_relation = "Milestones"
notion_tasks_sprint_relation = "Sprint"
notion_tasks_text_assignee = ""
notion_tasks_labels = ""
notion_milestones_title = "Name"
notion_milestones_team = "Team"
notion_milestones_assignee = "Assignee"
notion_milestones_priority = "Priority"
notion_milestones_dates = "Original Due Date"
notion_issue_field = "Bug URL"
notion_default_open_state = "Backlog"
notion_inprogress_state = "In progress"
notion_closed_states = ["Done"]
notion_tasks_repository = "Product (Services)"

[sync.services.properties.notion_tasks_repository_map]
"thunderbird/addons-server" = "Core Services"
"thunderbird/appointment" = "Appointment"
"thunderbird/cloudops" = "Core Services"
"thunderbird/mailstrom" = "Thundermail"
"thunderbird/observability" = "Pro General"
"thunderbird/pulumi" = "Pro General"
"thunderbird/send-suite" = "Send"
"thunderbird/services-ui" = "Pro General"
"thunderbird/services-utils" = "Pro General"
"thunderbird/tbpro-add-on" = "Send"
"thunderbird/thunderbird-accounts" = "Accounts"
"thunderbird/thunderbird-notifications" = "Core Services"
"thunderbird/thunderbird-website" = "Websites"
"thunderbird/thundernest-ansible" = "Core Services"

[sync.services_deployments]
method="github_deployments"
expected_columns = 4
stage_column = 3
prod_column = 4

[sync.services_deployments.blocks]
"thunderbird/tbpro-add-on" = "2332df5d45ae8073b22ed40032f0f440"
"thunderbird/appointment" = "2332df5d45ae80f98483cdd99603a862"
"thunderbird/thunderbird-accounts" = "27e2df5d45ae800c82f6e87f4527ce1e"
"thunderbird/mailstrom" = "2332df5d45ae802787cde66564c51d88"
