---
name: Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'

concurrency:
  group: synchronize
  cancel-in-progress: false


jobs:
  synchronize:
    if: ${{ github.repository_owner == 'thunderbird' }}
    uses: ./.github/workflows/run.yml
    secrets: inherit
    with:
      environment: production
