---
name: Notion Sync

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      projects:
        type: string
        required: false

  workflow_dispatch:
    inputs:
      environment:
        type: environment
      projects:
        type: string
        description: Enter one or more projects to sync. Leave empty for all.
      dry:
        type: boolean
        description: Do a dry run


jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      synchronizers: ${{ steps.generate.outputs.synchronizers }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b  # v6.6.0
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-nothing-to-cache: true

      - name: uv sync
        run: uv sync --locked --all-extras --dev

      - name: Generate
        id: generate
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PROJECTS: ${{ inputs.projects }}
        run: |
          if [ -z "${PROJECTS}" ]
          then
            echo "synchronizers=$(uv run -m mzla_notion -l -c config/sync_settings.${ENVIRONMENT}.toml | jq -R . | jq -sc .)" | tee -a $GITHUB_OUTPUT
          else
            echo "synchronizers=$(echo ${PROJECTS} | jq -R . | jq -sc .)" | tee -a $GITHUB_OUTPUT
          fi

  run:
    needs: setup-matrix
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      fail-fast: false
      matrix:
        synchronizer: ${{ fromJson(needs.setup-matrix.outputs.synchronizers) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5

      - name: Setup uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b  # v6.6.0
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-nothing-to-cache: true

      - name: uv sync
        run: uv sync --locked --all-extras --dev

      - name: Get repositories
        id: get-repos
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PROJECT: ${{ matrix.synchronizer }}
          VERBOSE: ${{ runner.debug && '-vv' || '' }}
          DRY: ${{ inputs.dry && '-n' || '' }}
        run: |
          # Note: create-app-token only works with one owner, we need to cut it here
          echo 'repositories<<EOF' >> $GITHUB_OUTPUT
          uv run -m mzla_notion ${DRY} ${VERBOSE} \
            -c config/sync_settings.${ENVIRONMENT}.toml \
            --repositories ${PROJECT} | cut -d / -f 2 | tee -a $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Get app token
        id: apptoken
        if: ${{ vars.GH_APP_ID }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: thunderbird
          repositories: ${{ steps.get-repos.outputs.repositories }}

      - name: Synchronize
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          PROJECT: ${{ matrix.synchronizer }}
          VERBOSE: ${{ runner.debug && '-vv' || '' }}
          DRY: ${{ inputs.dry && '-n' || '' }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ steps.apptoken.outputs.token || secrets.GH_PAT }}
          BUGZILLA_TOKEN: ${{ secrets.BUGZILLA_TOKEN }}
          NOTION_SYNC_GITHUB_USERMAP: ${{ vars.NOTION_SYNC_GITHUB_USERMAP }}
          NOTION_SYNC_BUGZILLA_USERMAP: ${{ vars.NOTION_SYNC_BUGZILLA_USERMAP }}
        run: |
          uv run -m mzla_notion ${DRY} ${VERBOSE} -c config/sync_settings.${ENVIRONMENT}.toml ${PROJECT}
